# Generated by Django 4.1 on 2023-12-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('cost', models.CharField(max_length=20)),
                ('deposit', models.CharField(max_length=20)),
                ('activity_price_deposit', models.CharField(max_length=20)),
                ('toplimit', models.CharField(max_length=20)),
                ('Statement', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pd',
            },
        ),
    ]
